# -*- coding: utf-8 -*-
"""LSTM with input as Technical indicators

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gF0uZdDNI6UWPZh3s2aFLzvHBgtNXsSi

**To create a dataset that includes various technical indicators such as SMA (Simple Moving Average), EMA (Exponential Moving Average), RSI (Relative Strength Index), MACD (Moving Average Convergence Divergence), and other features for the Bank Nifty index and its 12 constituent banks**

**Using an optimal LSTM architecture achieved after comparing the performance of different LSTM architectures as given in the following link:** https://colab.research.google.com/drive/1DyOIKsJEGfD6nqqDm5ZRbhZSrqIye9Aj?usp=sharing#scrollTo=jDwhIA6UugCh
"""

pip install ta

import pandas as pd
import ta
import yfinance as yf

# List of Bank nifty and its 12 constituent banks
stocks = {
    'Bank Nifty': '^NSEBANK',
    'HDFC Bank Ltd': 'HDFCBANK.NS',
    'ICICI Bank Ltd': 'ICICIBANK.NS',
    'Axis Bank Ltd': 'AXISBANK.NS',
    'State Bank of India': 'SBIN.NS',
    'Kotak Mahindra Bank Ltd': 'KOTAKBANK.NS',
    'Indusind Bank Ltd': 'INDUSINDBK.NS',
    'Bank of Baroda Ltd': 'BANKBARODA.NS',
    'Federal Bank Ltd': 'FEDERALBNK.NS',
    'Punjab National Bank': 'PNB.NS',
    'IDFC First Bank Ltd': 'IDFCFIRSTB.NS',
    'AU Small Finance Bank Ltd': 'AUBANK.NS',
    'Bandhan Bank Ltd': 'BANDHANBNK.NS'
}

# Initialize a DataFrame to store daily data for all stocks
all_data = pd.DataFrame()

# Fetch data for each stock and merge into one DataFrame
for stock, ticker in stocks.items():
    data = yf.download(ticker, start='2019-01-01', end='2024-04-01')
    all_data[stock + '_Close'] = data['Adj Close']

# Print the DataFrame
#print(all_data)

def add_technical_indicators(df, column_name):
# Create a working DataFrame just for this stock
    df_stock = pd.DataFrame(df[column_name])

    # Simple Moving Averages
    df_stock['SMA_20'] = df_stock[column_name].rolling(window=20).mean()
    df_stock['SMA_50'] = df_stock[column_name].rolling(window=50).mean()
    df_stock['SMA_200'] = df_stock[column_name].rolling(window=200).mean()

    # Exponential Moving Averages
    df_stock['EMA_20'] = df_stock[column_name].ewm(span=20, adjust=False).mean()
    df_stock['EMA_50'] = df_stock[column_name].ewm(span=50, adjust=False).mean()

    # RSI (Relative Strength Index)
    df_stock['RSI'] = ta.momentum.RSIIndicator(close=df_stock[column_name], window=14).rsi()

    # MACD (Moving Average Convergence Divergence)
    macd = ta.trend.MACD(close=df_stock[column_name])
    df_stock['MACD'] = macd.macd()
    df_stock['MACD_Signal'] = macd.macd_signal()
    df_stock['MACD_Hist'] = macd.macd_diff()

    return df_stock

# Initialize a dictionary to store the data for all stocks with their respective indicators
all_technical_data = pd.DataFrame()

# Iterate over each stock and compute technical indicators
for stock, ticker in stocks.items():
    column_name = stock + '_Close'
    stock_indicators = add_technical_indicators(all_data, column_name)

    # Add a prefix to each column to identify which stock the indicators belong to
    stock_indicators = stock_indicators.add_prefix(stock + '_')

    # Merge the stock's technical indicators into the main DataFrame
    if all_technical_data.empty:
        all_technical_data = stock_indicators
    else:
        all_technical_data = pd.concat([all_technical_data, stock_indicators], axis=1)

# Display the combined DataFrame with technical indicators
#print(all_technical_data)

# Step 1: Interpolate missing values linearly
all_technical_data.interpolate(method='linear', inplace=True)

# Step 2: Drop any remaining NaN values
all_technical_data.dropna(inplace=True)

all_technical_data.head()

# Sample size of the combined DataFrame
# Combined DataFrame includes (Bank nifty and its 12 constituent banks along with technical indicators)
all_technical_data.shape

"""**Predicting the next day's Bank Nifty closing price (regression)**"""

# Shift the target column to create labels for the next day (one-step ahead forecasting)
all_technical_data['Target'] = all_technical_data['Bank Nifty_Bank Nifty_Close'].shift(-1)

# Drop the last row (since it won't have a valid target value)
all_technical_data.dropna(inplace=True)

from sklearn.preprocessing import MinMaxScaler

# Select the features and target
features = all_technical_data.drop(columns=['Target'])  # All columns except the target
target = all_technical_data['Target']  # Target is next day's close price

# Initialize scalers
scaler_features = MinMaxScaler(feature_range=(0, 1))
scaler_target = MinMaxScaler(feature_range=(0, 1))

# Scale features and target
features_scaled = scaler_features.fit_transform(features)
target_scaled = scaler_target.fit_transform(target.values.reshape(-1, 1))

"""**Data Preparation for LSTM Modeling**

**Create 60-day historical sequences for next day price prediction**

**Split data into 80% training, 20% testing sets**
"""

import numpy as np

# Define sequence length
sequence_length = 60

def create_sequences(data, target, seq_length):
    X, y = [], []
    for i in range(len(data) - seq_length):
        X.append(data[i:i + seq_length])  # Sequence of `seq_length` days
        y.append(target[i + seq_length])  # The target is the value at `i + seq_length`
    return np.array(X), np.array(y)

# Create sequences
X, y = create_sequences(features_scaled, target_scaled, sequence_length)

from sklearn.model_selection import train_test_split

# Split data into training and testing sets (e.g., 80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# Create sequences
#X, y = create_sequences(features_scaled, target_scaled, sequence_length)
X_train.shape

X_test.shape

"""**LSTM Model Architecture and Training**"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# Build LSTM Model
model = Sequential()

# LSTM layer 1 (return_sequences=True for passing sequences to the next LSTM layer)
model.add(LSTM(units=100, return_sequences=True, input_shape=(sequence_length, X_train.shape[2])))
model.add(Dropout(0.5))  # Dropout for regularization

# LSTM layer 2 (final LSTM layer, no need for return_sequences)
model.add((LSTM(100, return_sequences=False)))
model.add(Dropout(0.5))

# Output layer for regression (1 neuron to predict next value)
model.add(Dense(1, activation='linear'))

# Compile the model (using mean squared error loss for regression)
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model with a validation split (no shuffle, as it's time-series data)
history = model.fit(X_train, y_train, validation_data=(X_test,y_test), epochs=40,batch_size=40, verbose=1, shuffle =True)

'''from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
history = model.fit(X_train, y_train, epochs=200, batch_size=100,
                    validation_split=0.2, shuffle=False, callbacks=[early_stopping])'''
# Check history for learning curves
print(history.history.keys())

#Disply a summary of the model's architecture
model.summary()

# Model Evaluation
import matplotlib.pyplot as plt

# Plot the training and validation loss
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

# 7. Predict on the Test Set
predictions = model.predict(X_test)

# Reverse the scaling for target values to get predictions in the original scale
predictions_rescaled = scaler_target.inverse_transform(predictions)
y_test_rescaled = scaler_target.inverse_transform(y_test)

# Evaluate Model Performance
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Calculate overall Mean Squared Error (MSE) and Root Mean Squared Error (RMSE)
mse = mean_squared_error(y_test_rescaled, predictions_rescaled)
rmse = np.sqrt(mse)

print(f"Overall Mean Squared Error: {mse}")
print(f"Overall Root Mean Squared Error: {rmse}")

# Plotting actual vs predicted values
plt.figure(figsize=(20,3))
plt.plot(y_test_rescaled, color='blue', label='Actual Price')
plt.plot(predictions_rescaled, color='red', label='Predicted Price')
plt.title('Actual vs Predicted Prices')
plt.xlabel('Time')
plt.ylabel('Price')
plt.legend()
plt.show()