# -*- coding: utf-8 -*-
"""LSTM Implementation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DyOIKsJEGfD6nqqDm5ZRbhZSrqIye9Aj

**Data Loading**

**Download historical stock price data from Yahoo Finance**
"""

#Import necessary libraries
import pandas as pd
import yfinance as yf
from sklearn.preprocessing import MinMaxScaler
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Reshape, Dropout
from sklearn.metrics import mean_squared_error
import datetime

# Define the stocks and their tickers
stocks = {
    'Bank Nifty': '^NSEBANK',
    'HDFC Bank Ltd': 'HDFCBANK.NS',
    'ICICI Bank Ltd': 'ICICIBANK.NS',
    'Axis Bank Ltd': 'AXISBANK.NS',
    'State Bank of India': 'SBIN.NS',
    'Kotak Mahindra Bank Ltd': 'KOTAKBANK.NS',
    'Indusind Bank Ltd': 'INDUSINDBK.NS',
    'Bank of Baroda Ltd': 'BANKBARODA.NS',
    'Federal Bank Ltd': 'FEDERALBNK.NS',
    'Punjab National Bank': 'PNB.NS',
    'IDFC First Bank Ltd': 'IDFCFIRSTB.NS',
    'AU Small Finance Bank Ltd': 'AUBANK.NS',
    'Bandhan Bank Ltd': 'BANDHANBNK.NS'
}

# Initialize a DataFrame to store daily data for all stocks
all_data = pd.DataFrame()

# Fetch data for each stock and merge into one DataFrame
for stock, ticker in stocks.items():
    data = yf.download(ticker, start='2019-01-01', end='2024-04-01')
    all_data[stock + '_Close'] = data['Adj Close']

# Print the DataFrame
#print(all_data)

"""**Data Preprocessing**"""

# Drop rows with any missing values (considering interpolation for better handling)
all_data.interpolate(method='linear', inplace=True)
all_data.dropna(inplace=True)

# Function to smooth outliers based on IQR (Interquartile Range) method
def smooth_outliers(df):
    for column in df.columns:
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        # Replace outliers with median
        median = df[column].median()
        df[column] = df[column].apply(lambda x: median if x < lower_bound or x > upper_bound else x)
    return df

# Smooth outliers in the data
all_data_smoothed = smooth_outliers(all_data)

# Normalize the data using MinMaxScaler
scaler = MinMaxScaler()
all_data_scaled = pd.DataFrame(scaler.fit_transform(all_data_smoothed), index=all_data.index, columns=all_data.columns)

all_data_scaled.head()

"""**Visualize the historical closing prices of Bank Nifty and its Constituents**"""

import matplotlib.pyplot as plt
# Set up the subplots
num_stocks = len(stocks)
cols = 4
rows = (num_stocks + cols - 1) // cols

fig, axes = plt.subplots(rows, cols, figsize=(18, 18))
fig.suptitle('Historical Closing Prices of Bank Nifty and Its Constituents', fontsize=20)

# Flatten the axes array for easy iteration
axes = axes.flatten()

# Plot each stock's closing price
for i, (stock, ticker) in enumerate(stocks.items()):
    axes[i].plot(all_data.index, all_data[stock + '_Close'], label=stock)
    axes[i].set_title(stock)
    axes[i].set_xlabel('Date')
    axes[i].set_ylabel('Adjusted Close Price')
    axes[i].legend()

# Remove any empty subplots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""**Visualize Correlation between the stocks**"""

import seaborn as sns
# Visualize correlation between stocks
correlation_matrix = all_data.corr()
plt.figure(figsize=(10,5))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Matrix of Stock Prices')
#plt.savefig('correlation_matrix.png')
plt.show()

"""**Data Preparation for LSTM Modeling:**

*  **Create 60-day historical sequences for 5-day price prediction**
*  **Split data into 80% training, 20% testing sets**
"""

# Function to create sequences for LSTM
def createSequences(data, sequenceWindow, weekWindow):
    X, y = [], []
    for i in range(len(data) - sequenceWindow - weekWindow):
        X.append(data[i:(i + sequenceWindow)])
        y.append(data[(i + sequenceWindow):(i + sequenceWindow + weekWindow)])
    return np.array(X), np.array(y)

# Choose sequence length - 60 days = 12 weeks
sequenceWindow = 60
weekWindow = 5
X, y = createSequences(all_data_scaled.values, sequenceWindow, weekWindow)

# Split data into training and testing sets - 80:20 split
train_size = int(0.8 * len(X))
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

"""**LSTM Model Architecture and Training**"""

# Build LSTM model
model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(sequenceWindow, all_data_scaled.shape[1])))
model.add(Dropout(0.2))
model.add(LSTM(units=100))
model.add(Dropout(0.2))
model.add(Dense(5 * 13))  # 5 days * 13 stocks
model.add(Reshape((5, 13)))  # Reshape to match the target shape

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
history= model.fit(X_train, y_train, epochs=200, batch_size=100, validation_split=0.2)

# Check history for learning curves
print(history.history.keys())

import matplotlib.pyplot as plt

# Plot training and validation loss
plt.figure(figsize=(10, 6))
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('LSTM model performance_phase1')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

#Disply a summary of the model's architecture
model.summary()

"""**Model Evaluation and Performance Metrics:**

*  **Generate predictions and inverse transform to original scale**
*  **Calculate MSE and RMSE for overall model performance**
*  **Compute specific RMSE for Bank Nifty index**
"""

# Make predictions, reshaping to match y_test
y_pred_scaled = model.predict(X_test).reshape(y_test.shape)

# Inverse transform the predictions
y_pred = scaler.inverse_transform(y_pred_scaled.reshape(-1, all_data_scaled.shape[1])).reshape(y_test.shape)

# Calculate MSE for each stock and each day
mse_per_stock_day = np.zeros((y_test.shape[1], y_test.shape[2]))
for stock_idx in range(y_test.shape[1]):
    for day_idx in range(y_test.shape[2]):
        mse_per_stock_day[stock_idx, day_idx] = mean_squared_error(
            y_test[:, stock_idx, day_idx], y_pred[:, stock_idx, day_idx]
        )

# Calculate overall MSE
overall_mse = np.mean(mse_per_stock_day)

# Calculate RMSE
overall_rmse = np.sqrt(overall_mse)

print("Overall MSE:", overall_mse)
print("Overall RMSE:", overall_rmse)

# Calculate RMSE for Bank Nifty - first column
bank_nifty_mse = np.mean(mse_per_stock_day[0, :])  # Average over days
bank_nifty_rmse = np.sqrt(bank_nifty_mse)

print("Bank Nifty RMSE:", bank_nifty_rmse)

"""**Model Prediction**"""

# Prepare the most recent data for prediction
latest_data = all_data_scaled.values[-sequenceWindow:]
X_pred = latest_data.reshape(1, sequenceWindow, all_data_scaled.shape[1])

# Use the trained model to make predictions
y_pred_scaled = model.predict(X_pred)

# Inverse transform the predictions to get actual values
y_pred = scaler.inverse_transform(y_pred_scaled.reshape(-1, all_data_scaled.shape[1]))

# Extract and format the predictions
last_date = all_data.index[-1]
prediction_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=5)
predictions = pd.DataFrame(y_pred, columns=all_data.columns, index=prediction_dates)

# Display the predictions
print("Predictions for the next 5 days:")
print(predictions)

# Optionally, you can focus on specific stocks, e.g., Bank Nifty
print("\nBank Nifty predictions:")
print(predictions['Bank Nifty_Close'])